name: Measure Store lighthouse

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./front-metrics
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"
          cache: "yarn"
          cache-dependency-path: ./front-metrics/yarn.lock

      - name: Install packages.
        run: yarn --frozen-lockfile

      - name: Run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.11.x
          lhci autorun

      - name: Measure score and send data.
        run: yarn lighthouse
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
