name: Measure Store lighthouse

on:
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./front-metrics
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version-file: ./front-metrics/.node-version
          cache: "yarn"
          cache-dependency-path: ./front-metrics/yarn.lock

      - name: Install packages.
        run: yarn --frozen-lockfile

      - name: Run Lighthouse CI
        run: npx @lhci/cli@0.12.0 collect --numberOfRuns=1 --url=https://stores-gallery.shop

      - name: Measure score and send data.
        run: yarn lighthouse
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
